apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-cloudcore
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10000
    name: cloudhub
  - port: 10002
    name: cloudhub-cert
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: NodePort
