apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ .Release.Name}}-kubeedge
    kubeedge: {{ .Release.Name}}-cloudcore
  name: {{ .Release.Name}}-cloudcore
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name}}-kubeedge
      kubeedge: {{ .Release.Name}}-cloudcore
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name}}-kubeedge
        kubeedge: {{ .Release.Name}}-cloudcore
    spec:
      hostNetwork: true
      containers:
      - name: cloudcore
        image: kubeedge/cloudcore:v1.7.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
          name: cloudhub
          protocol: TCP
        - containerPort: 10002
          name: cloudhub-cert
          protocol: TCP
        - containerPort: 10001
          name: cloudhub-quic
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: conf
          mountPath: /etc/kubeedge/config
        - name: certs
          mountPath: /etc/kubeedge
        - name: sock
          mountPath: /var/lib/kubeedge
      restartPolicy: Always
      serviceAccount: {{ .Release.Name}}-cloudcore
      serviceAccountName: {{ .Release.Name}}-cloudcore
      volumes:
      - name: conf
        configMap:
          name: {{ .Release.Name}}-cloudcore
      - name: certs
        hostPath:
          path: /etc/kubeedge
          type: DirectoryOrCreate
      - name: sock
        hostPath:
          path: /var/lib/kubeedge
          type: DirectoryOrCreate

