apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-cloudcore
  labels:
    k8s-app: {{ .Release.Name}}-kubeedge
    kubeedge: {{ .Release.Name}}-cloudcore
spec:
  ports:
  - port: 10000
    name: cloudhub
  - port: 10001
    name: cloudhub-quic
  - port: 10002
    name: cloudhub-cert
  selector:
    k8s-app: {{ .Release.Name}}-kubeedge
    kubeedge: {{ .Release.Name}}-cloudcore
  type: NodePort
